algoritmo "semnome"
// Função :
// Autor :
// Data : 18/02/2025
// Seção de Declarações 
var
pessoa:vetor[1..4] de caractere
indice: inteiro

inicio
// Seção de Comandos

para indice de 1 ate 4 faca
escreval("Insira os seguintes dados: Nome, Renda, Idade e Profissão")
leia(pessoa[indice])
fimpara
para indice de 1 ate 4 faca
escreval("Conferência de dados",indice," :",pessoa[indice])
fimpara




 
fimalgoritmo


