algoritmo "Primeiro Programa"
// Função :
// Autor : Isaac Gomes
// Data : 10/02/2025
// Seção de Declarações 
var
estudante: caracter
nota1: real
nota2: real
resultado: real

inicio
// Seção de Comandos 
escreval("Por favor insira o nome do(a) aluno(a):")
leia(estudante)

escreval("Insira a primeira nota:")
leia(nota1)

escreval("insira a segunda nota:")
leia(nota2)

resultado <- (nota1+nota2)/2

escreval("A média do(a) aluno(a) é:",resultado)

fimalgoritmo
